### ISSUE TITLE
无法正常连接,输入完账号密码正确之后,LinkHome方法里面Connection: close

### ISSUE THREAD

**Issue by bq1122** [bjdgyc/anylink#1]
DumpHome:  GET / HTTP/1.0
Host: 127.0.0.1
Connection: close
Connection: Close
Content-Length: 0
User-Agent: Cisco AnyConnect VPN Agent for Windows 4.9.04053
User-Agent: AnyConnect Agent 4.9.04053
X-Transcend-Version: 1

**Comment by bjdgyc** [comment]
你好，麻烦提供下版本号
`./anylink -rev`
另外，账号登陆方式为：
group
