### ISSUE TITLE
禁用top一直登录不上

### ISSUE THREAD

**Issue by omaidb** [bjdgyc/anylink#192]
禁用top一直登录不上,反复提示密码错误

**Comment by omaidb** [comment]
第一次安装,还没成功登录过一次

**Comment by lanrenwo** [comment]
建议添加QQ群: 567510628

**Comment by omaidb** [comment]
> 建议添加QQ群: 567510628

谢谢，不加，在这回答解决问题能帮助到其他人

**Comment by 0x0021** [comment]
> 

起码加个日志截图啥的

**Comment by omaidb** [comment]
![正在上传 202341352...]

**Comment by omaidb** [comment]
![image](https://user-images.githubusercontent.com/18365223/202641610-be2c1b7d-b1ae-4416-914c-01be25f416d6.png)
日志我去看看

**Comment by omaidb** [comment]
日志全文如下.
[anylink.log](https://github.com/bjdgyc/anylink/files/10038890/anylink.log)

**Comment by bjdgyc** [comment]
用户组状态开启一下

**Comment by omaidb** [comment]
> 
搜嘎,用户组默认竟然是禁用的,吃惊

**Comment by omaidb** [comment]
启用用户组后可以登录上了.

**Comment by omaidb** [comment]
感谢大佬
