### ISSUE TITLE
affected/package: v0.9.2-beta2

### ISSUE THREAD

**Issue by zhongheng666** [bjdgyc/anylink#218]
### 使用的anylink版本 ?

v0.8.1至v0.9.2-beta2
### 使用操作系统的类型和版本?

Debian 11.6.0
### 使用linux 内核版本?

Linux dns1 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux

### 具体遇到的问题，可上传截图

用户在登录过程中，会频繁出现动态码错误的情况，但是核实其OTP码并没有问题，删除OTP重新生成绑定后与删除账号重建还是如此
![image](https://user-images.githubusercontent.com/14886041/212590232-9f2d2ec2-99ab-4627-8efe-d426efc03a65.png)

**Comment by lanrenwo** [comment]
建议检查一下客户端和服务器端的时间是否一致，强烈建议添加QQ群: 567510628，群里很多大佬。

**Comment by zhongheng666** [comment]
第一、我服务器时间是正确的，且这个问题在Ubuntu 22.04.1 LTS中也会有几率出现，只是概率没有Debian上那么大。
第二、加群并不能解决问题，因为我本身在群里，我除了能看到几个爱装B的一直在群里逼逼叨叨我没看到任何对解决这个问题有用的信息。
第三、你作为一个代码贡献者，首先我要感谢你的贡献，但是我觉得你回答issue首要的应该是尽量复现问题从而分析问题，而不是让人加群，还是上面那句，群里有大佬但很少说话，只有爱装逼的几个在逼逼叨叨。
第四、我作为一个不会写代码的人，这个回复并不是针对你或者谁，如果你觉得这个回复让你感到不适我可以删掉这个issue。

**Comment by zhongheng666** [comment]
鉴于我的回复第二条内容刺激到了群里的很多“大佬”，为避免玻璃心“大佬”到这里污染github的环境，所以issue关闭，祝各位口吐芬芳的“大佬”全家幸福啊！
