### ISSUE TITLE
SSLVPN behind Cloudflare

### ISSUE THREAD

**Issue by singhigh** [bjdgyc/anylink#220]
使用Letsencrypt签发SSL证书，套了CF，访问https://sslvpn， 正常绿标，但是客户端访问总是失败，是否是因为server的证书和CDN的证书不一致所致？是否有解决方案？谢谢。

**Comment by bjdgyc** [comment]
目前仅支持四层代理，不支持http七层代理

**Comment by singhigh** [comment]
Thanks, 兔年大吉~
