### ISSUE TITLE
请问是否可以返回错误消息提示给anyconnect吗?

### ISSUE THREAD

**Issue by LookingDreamer** [bjdgyc/anylink#223]
### 使用的anylink版本 ?

AnyLink v0.9.1-beta1

<pre>
./anylink tool -v
管理后台也可以查看
</pre>

### 使用操作系统的类型和版本?
CentOS Linux release 7.9.2009 (Core)

<pre>
cat /etc/issue
cat /etc/redhat-release

</pre>

### 使用linux 内核版本?
Linux 25ec3d9a4bf6 3.10.0-862.el7.x86_64
<pre>
uname -a

</pre>

### 具体遇到的问题，可上传截图

比如我添加了mac绑定功能,用户mac不匹配,怎么返回错误消息给anyconnect弹窗?

**Comment by bjdgyc** [comment]
直接返回错误信息给到用户，可能会导致信息泄露，这个考虑后期加一个开关吧

**Comment by bjdgyc** [comment]
> > 直接返回错误信息给到用户，可能会导致信息泄露，这个考虑后期加一个开关吧
> 
> 你的qq群还在？

qq群 567510628
现在可以了
