### ISSUE TITLE
同一个客户端，ip映射却不断新建

### ISSUE THREAD

**Issue by bettswang** [bjdgyc/anylink#230]
### 使用的anylink版本 ?

<pre>
AnyLink v0.9.1-beta1
</pre>

### 使用操作系统的类型和版本?

<pre>
Ubuntu 20.04.4 
</pre>

### 使用linux 内核版本?

<pre>
5.4.0-146-generic
</pre>

### 具体遇到的问题，可上传截图
在windows下，使用openconnect-ui客户端进行拨号，每次登录都会生成一个新的ip映射，看mac地址每次都是随机生成的。这种情况下，很容易ip池就被用光了。有什么办法可以解决吗？

![图片](https://user-images.githubusercontent.com/43665641/231030726-6ad2c589-a114-4e30-a44f-2ccf4188a974.png)

**Comment by bettswang** [comment]
anylink-client安装后，有错误。重装后还是报这个错误
![图片](https://user-images.githubusercontent.com/43665641/231080428-9004fa5a-0e6a-48fe-b6c2-e324486c7917.png)

**Comment by itviewer** [comment]
> anylink-client安装后，有错误。重装后还是报这个错误
> 
> ![图片](https://user-images.githubusercontent.com/43665641/231080428-9004fa5a-0e6a-48fe-b6c2-e324486c7917.png)
> 
> 

能准确的描述下操作系统版本号吗，或者把安装过程用手机录个视频？我发现有些人也有这个问题，但我自己电脑不会出现，可能是软件确实有些地方没考虑到，毕竟每个人的电脑环境差异很大，要是能帮忙发下问题就好了

**Comment by bettswang** [comment]
安装过程：
![图片](https://user-images.githubusercontent.com/43665641/231085743-baccc1c7-fd60-44c4-a983-45f404d4aab9.png)
![图片](https://user-images.githubusercontent.com/43665641/231085858-d6b9c56a-1e39-4bd4-a935-0985e62b356c.png)
这一步会卡住，但是后面也会完成安装
![图片](https://user-images.githubusercontent.com/43665641/231086069-1d398221-2d65-43f5-a2e8-28e48f50e31e.png)
![图片](https://user-images.githubusercontent.com/43665641/231086114-5406a268-5f0b-423e-b7de-c225ed87ff83.png)


操作系统版本：
![图片](https://user-images.githubusercontent.com/43665641/231086400-581cf1c7-7a51-4750-a5cc-eca80360fe3d.png)
软件版本：
![图片](https://user-images.githubusercontent.com/43665641/231086232-0acce9ea-4c39-48b3-b95b-8ae10d2a92eb.png)

**Comment by bettswang** [comment]
好奇怪，现在就可以了。我重装了4-5遍，也重启过电脑了。刚才还不行，现在突然就可以了

**Comment by itviewer** [comment]
> 好奇怪，现在就可以了。我重装了4-5遍，也重启过电脑了。刚才还不行，现在突然就可以了

我目前只能猜测问题是界面启动的太快了，软件安装完后会先启动VPNAgent系统服务，界面再连接到系统服务，可能是服务还没起来，界面就先打开了，导致出现这种情况，关闭软件再打开应该就好了，我先按这个思路优化下软件，谢谢

**Comment by itviewer** [comment]
> 也是有这个可能性的，但是我之前安装好后，也是反复启动关闭好几次，之前都是不行的。这个客户端现在有mac版本吗？

没有，因为我没有mac电脑！如果自己懂点Go语言，移植也很容易

**Comment by bjdgyc** [comment]
可以使用群里面的 anyconnect 客户端

**Comment by bettswang** [comment]
> 可以使用群里面的 anyconnect 客户端

anyconnect 对于vpn server端是自签证书的，好像不支持。

**Comment by bettswang** [comment]
![图片](https://user-images.githubusercontent.com/43665641/231327264-551ebcb1-791d-4183-9e71-80ff8ae161ce.png)
看了下服务，确实没有启动起来

**Comment by itviewer** [comment]
目前猜测可能和WiFi有关，在客户端下载页面加客户端的QQ群，我可以帮忙看看到底是什么问题

**Comment by bettswang** [comment]
新版客户端已经接近这个bug了。此问题，我就关闭了。
