### ISSUE TITLE
i wanna help you

### ISSUE THREAD

**Issue by amir0241** [bjdgyc/anylink#238]
hi bro , i saw how your project is great and im actully from iran so i wanna to help you develop this project more.
i can translate your project to english and also i have an idea to improve in connecting , is there anyway to support cloudflare cdn proxy?
if it can, how can we connect through that ?

**Comment by bjdgyc** [comment]
Thank you，anylink just support L4 proxy！

**Comment by amir0241** [comment]
but layer4 proxy is not accessible by any person , can't we make this support a normal cdn from cloudflare?

**Comment by itviewer** [comment]
相信你能看懂中文，ssl vpn并不工作在http层，而是工作在tcp或者udp层，ssl vpn并不是一个http/https应用。

我不知道你的想法是否受到某些中文互联网内容的影响，在中文互联网上，有些人认为ssl vpn只需要一个浏览器就可以了，连客户端都不需要，这些人根本就不懂ssl vpn的工作原理，他们混淆了http代理和vpn的概念，人云亦云，这种毫无技术含量的内容在中文互联网上大量存在。
如果你想在ssl vpn上面加一层代理，你必须在tcp而不是http层面进行流量转发。
