### ISSUE TITLE
anyconnect连接报错 [Error] tun Read err 0 read tun: file already closed

### ISSUE THREAD

**Issue by PolarisTime** [bjdgyc/anylink#239]
### 使用的anylink版本 ?
0.9.3 

### 使用操作系统的类型和版本?
Rocky Linux release 9.1 (Blue Onyx)

### 使用linux 内核版本?
Linux PolarisTime 5.14.0-162.23.1.el9_1.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Apr 11 19:09:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### 具体遇到的问题，可上传截图
第一次正常调通 连接正常 访问内网正常 

尝试安装systemd服务，启动正常，客户端连接报错 [Error] tun Read err 0 read tun: file already closed

使用命令行启动连接继续提示报错 [Error] tun Read err 0 read tun: file already closed

客户端版本
<img width="493" alt="Snipaste_2023-05-04_13-45-10" src="https://user-images.githubusercontent.com/38488283/236121114-eb3c2305-131a-43c6-8fd5-f7ec3c5d1bab.png">

附LOG 
[anylink.output.log](https://github.com/bjdgyc/anylink/files/11394038/anylink.output.log)

**Comment by PolarisTime** [comment]
附配置文件
[server.toml.txt](https://github.com/bjdgyc/anylink/files/11394116/server.toml.txt)

**Comment by bjdgyc** [comment]
配置错误，去掉这一条 `X-CSTP-Split-Exclude: 0.0.0.0/0.0.0.0`
`
