### ISSUE TITLE
编译报错Error parsing reference: "node:lts-alpine as builder_node" is not a valid repository/tag: invalid reference format

### ISSUE THREAD

**Issue by cqkenuo** [bjdgyc/anylink#24]
Error parsing reference: "node:lts-alpine as builder_node" is not a valid repository/tag: invalid reference format

**Comment by bjdgyc** [comment]
我这边测试docker编译是没有问题的，你试下以下命令是否正常
`docker pull node:lts-alpine`
然后提供下你的docker版本，看下是否支持多阶段构建
