### ISSUE TITLE
affected/package: 

### ISSUE THREAD

**Issue by Cole-GG** [bjdgyc/anylink#257]
local error: tls: bad record MAC 连接不上 报错 

### 使用的anylink版本 ?

<pre>
./anylink tool -v
AnyLink v0.6.2 build on go1.16.7 [linux, amd64] commit_id(ca4626879dbb9b13dd082c4412330338bfa64688)
管理后台也可以查看
</pre>

### 使用操作系统的类型和版本?
如： mac电脑上面docker安装的测试环境
<pre>
cat /etc/issue
cat /etc/redhat-release

</pre>

### 使用linux 内核版本?
<pre>
uname -a
Linux fe061571c8df 5.10.76-linuxkit #1 SMP Mon Nov 8 10:21:19 UTC 2021 x86_64 Linux
</pre>

**Comment by Lvmoo** [comment]
我遇到了相同的问题，使用的是容器部署
bash-5.1# ./anylink tool -v
AnyLink v0.9.4 build on go1.19.8 [linux, amd64] commit_id(28ffda23718a7576962e5bcfdbdf5895a8ee553f) 
bash-5.1# cat /etc/issue
Welcome to Alpine Linux 3.15
Kernel \r on an \m (\l)
bash-5.1# uname -a
Linux 00c576a8ca23 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 Linux

![image](https://github.com/bjdgyc/anylink/assets/20103297/902644ba-6e6c-4249-904b-ab514cfb06ef)
