### ISSUE TITLE
客户端连接时，提示未能下载 AnyConnect 配置文件。请重试。

### ISSUE THREAD

**Issue by podradio** [bjdgyc/anylink#263]
### 使用的anylink版本 ?
docker 0.94 镜像
AnyLink v0.9.4 build on go1.19.12 [linux, amd64] commit_id()                                             

<pre>
./anylink tool -v
管理后台也可以查看
</pre>

### 使用操作系统的类型和版本?
如： centos 7.9
<pre>
cat /etc/issue
cat /etc/redhat-release

</pre>
docker
### 使用linux 内核版本?
<pre>
uname -a

</pre>
群晖docker

### 具体遇到的问题，可上传截图
客户端链接时，提示未能下载 AnyConnect 配置文件。请重试。
![IMG_7431](https://github.com/bjdgyc/anylink/assets/51530402/418dcdd2-291c-4778-a904-48195c1da30b)
客户端版本：
![IMG_7434](https://github.com/bjdgyc/anylink/assets/51530402/852d2fd3-00c4-45ca-ae75-504e62d53c81)
看后台有成功登入日志，但很快就主动断开了链接
<img width="808" alt="image" src="https://github.com/bjdgyc/anylink/assets/51530402/ff405476-9b29-493f-9bd1-21f71d5545b2">

**Comment by bjdgyc** [comment]
你是不是修改 `profile.xml`  这个文件了

**Comment by podradio** [comment]
感谢您的回复，我用的最新的镜像(0.94)在 docker 里启动的时候报错：“panic: open ./conf/profile.xml: no such file or directory”
于是从 github 的项目里复制了项目里的profile.xml文件到了 ./conf 里，是否跟这个有关

**Comment by bjdgyc** [comment]
有关系

**Comment by podradio** [comment]
😭，我自己映射了一个 conf 配置的文件夹，然后把profile.xml文件方了进去

**Comment by podradio** [comment]
请教一下正确的profile.xml文件，怎么去获得？因为没有profile.xml文件，镜像起不起来。。。
