### ISSUE TITLE
affected/package: 后期会推出一键安装脚本吗？

### ISSUE THREAD

**Issue by do02fw** [bjdgyc/anylink#265]
后期会推出一键安装脚本吗？比如运行脚本后自动安装环境并且编译然后安装程序，安装完成直接显示地址和用户名密码。
### 使用的anylink版本 ?

<pre>
./anylink tool -v
管理后台也可以查看
</pre>

### 使用操作系统的类型和版本?
如： centos 7.9
<pre>
cat /etc/issue
cat /etc/redhat-release

</pre>

### 使用linux 内核版本?
<pre>
uname -a

</pre>

**Comment by zisain** [comment]
自己写一个检测系统版本的,然后拉取对应的路径解压下,,最后启动,这个没太多难题啊

**Comment by 0x0021** [comment]
Docker 不香吗

**Comment by zisain** [comment]
> Docker 不香吗

你也是个人才....有些人他没学过docker,也有些人就不喜欢更加复杂的网络环境,还有一些人就厌恶docker,,你怎么搞?
人家问能不能写一个一键部署,,,你却告诉人家用docker...人家就喜欢裸金属,你不就是在跟人扯淡?

**Comment by 0x0021** [comment]
> > Docker 不香吗
> 
> 你也是个人才....有些人他没学过docker,也有些人就不喜欢更加复杂的网络环境,还有一些人就厌恶docker,,你怎么搞? 人家问能不能写一个一键部署,,,你却告诉人家用docker...人家就喜欢裸金属,你不就是在跟人扯淡?

不爽你咋不写一个，乞丐吗，你要你的，别人不一定施舍
