### ISSUE TITLE
最新代码跑起来后台直接 404

### ISSUE THREAD

**Issue by changchunhua2017** [bjdgyc/anylink#3]
**环境**：
OS： centos 7.9 2009 latest 
 git clone 最新得 master 代码 （2021年-1月-11号  周一）

**安装的 golang 版本**：
golang-1.15.5-1.el7.x86_64
golang-bin-1.15.5-1.el7.x86_64
golang-src-1.15.5-1.el7.noarch

按 README一路编译正常 ， 运行后，前台 https://sslvpn.xxx.org 访问正常 ( 输出 hello world )，
访问 http://sslvpn.xxx.org:8800/ui/   后台页面 ，直接报 404

日志无任何新增输出信息 ，log_level info 调为 debug 测试依旧无新增输出信息 

**server.toml 配置文件**

```#服务配置信息

#其他配置文件,可以使用绝对路径
#或者相对于server.toml的路径

#数据文件
db_file = "./data.db"
#证书文件
cert_file = "./sslvpn.pem"
cert_key = "./sslvpn.key"
ui_path = "../ui"
down_files_path = "../down_files"

log_level = "debug"

#系统名称
issuer = "xxx sslvpn"
#后台管理用户
admin_user = "root"
#pass 123456
admin_pass = "$2a$10$/ZKjHF1Gtx40/S9DP29WkO/VmHq2Q0usRcsHUqey7T1cjD040vre2"
jwt_secret = "0c0Jy9fY47upxjwoea33DxvRN4TGdqD0YxjCcd9MwXuAjJVwc3280tBAuK4yw-ezqFqV"


#vpn服务对外地址
link_addr = "sslvpn.xxx.org"

#前台服务监听地址
server_addr = ":443"
#后台服务监听地址
admin_addr = ":8800"
#开启tcp proxy protocol协议
proxy_protocol = false

link_mode = "tun"

#客户端分配的ip地址池
ipv4_network = "5.5.5.0"
ipv4_netmask = "255.255.255.0"
ipv4_gateway = "5.5.5.1"
ipv4_pool = ["5.5.5.10", "5.5.5.20"]

#最大客户端数量
max_client = 100
#单个用户同时在线数量
max_user_client = 3
#IP租期(秒)
ip_lease = 1209600

#默认选择的组
default_group = "one"

#客户端失效检测时间(秒) dpd > keepalive
cstp_keepalive = 20
cstp_dpd = 30
mobile_keepalive = 50
mobile_dpd = 60
#session过期时间，用于断线重连，0永不过期
session_timeout = 3600
auth_timeout = 0```

**Comment by changchunhua2017** [comment]
仔细查看 README，看有提到 go version = 1.16  ,   于是卸载 1.15 版本，   source code 重新安装了  go 1.16 

**[root@anylink anylink-deploy]# go version
go version go1.16beta1 linux/amd64**

结果依旧 ，还是 404 错误

**Comment by bjdgyc** [comment]
你好，ui路径显示404的问题已经修复，请重新下载最新代码体验，另感谢提出该问题！

**Comment by changchunhua2017** [comment]
> 你好，ui路径显示404的问题已经修复，请重新下载最新代码体验，另感谢提出该问题！

 早上来了测试 OK ，404 问题解决，后台已正常登录  ！ 棒 ~
