### ISSUE TITLE
affected/package: 无法编译出主程序二进制文件

### ISSUE THREAD

**Issue by hjfxyz** [bjdgyc/anylink#303]
### 使用的anylink版本 ?
AnyLink v0.11.3
<pre>
./anylink tool -v
管理后台也可以查看
</pre>

### 使用操作系统的类型和版本?
如： debian12
<pre>
cat /etc/issue
cat /etc/redhat-release

</pre>

### 使用linux 内核版本?
<pre>
uname -a
6.1
</pre>

### 具体遇到的问题，可上传截图
无法编译出二进制文件
但是v0.11.2 build.sh文件拿过去就可以编译

**Comment by bjdgyc** [comment]
使用最新版
```
bash build_web.sh
bash build.sh
```
