### ISSUE TITLE
Gmail QR Code無正常顯示

### ISSUE THREAD

**Issue by taiwan-king** [bjdgyc/anylink#307]
相關資訊提供:
![01](https://github.com/bjdgyc/anylink/assets/24381898/8da13dce-a9a5-4c5f-b7ee-850d0d81396a)
![02](https://github.com/bjdgyc/anylink/assets/24381898/85236a09-d1d6-4004-999a-7d45810408e1)

目前遇到的問題:
gmail的QR Code無法正常顯示,猜測是google的阻擋問題
是否可以用連結或附檔的方式顯示QR Code?
![03](https://github.com/bjdgyc/anylink/assets/24381898/ca03c264-7ed4-49f2-85d7-29372da7b118)
自架mail server顯示正常
![04](https://github.com/bjdgyc/anylink/assets/24381898/b6c12268-9f5d-4a2e-95ad-f5ab5b11b0fa)

感謝您

**Comment by bjdgyc** [comment]
可以暂时使用以下代码 

```
用户动态码(3天后失效):<br/>
<img src="{{.OtpImg}}"/>
```

**Comment by taiwan-king** [comment]
> 可以暂时使用以下代码
> 
> ```
> 用户动态码(3天后失效):<br/>
> <img src="{{.OtpImg}}"/>
> ```

可以使用,感謝您

**Comment by bjdgyc** [comment]
修复google gmail不显示的问题了，可以自行编译体验 

https://github.com/bjdgyc/anylink/commit/e5c6533c9be9e2625a69608d0934361dc82ea6c7
