### ISSUE TITLE
build.sh遇错

### ISSUE THREAD

**Issue by luckypoem** [bjdgyc/anylink#33]
hi.

root@p1601860745:~/anylink# ./build.sh
++ pwd
+ cpath=/root/anylink
+ echo 编译二进制文件
编译二进制文件
+ cd /root/anylink/server
++ git rev-parse HEAD
+ go build -v -o anylink -ldflags '-X main.COMMIT_ID=cd8922237f6c9770faee52dd9e16d1757f9d0eb1'
go: downloading github.com/google/gopacket v1.1.19
go: downloading github.com/gorilla/mux v1.8.0
go: downloading github.com/pion/logging v0.2.2
go: downloading github.com/songgao/packets v0.0.0-20160404182456-549a10cd4091
go: downloading github.com/songgao/water v0.0.0-20200317203138-2b4b6d7c09d8
go: downloading github.com/fsnotify/fsnotify v1.4.7
go: downloading github.com/shirou/gopsutil v3.21.4+incompatible
go: downloading github.com/skip2/go-qrcode v0.0.0-20200617195104-da1b6568686e
go: downloading github.com/xhit/go-simple-mail/v2 v2.9.0
go: downloading github.com/asdine/storm/v3 v3.2.1
go: downloading github.com/xlzd/gotp v0.0.0-20181030022105-c8557ba2c119
go: downloading golang.org/x/net v0.0.0-20210520170846-37e1c6afe023
go: downloading github.com/pion/transport v0.12.3
go: downloading github.com/pion/udp v0.1.1
go: downloading github.com/tklauser/go-sysconf v0.3.6
go: downloading github.com/tklauser/numcpus v0.2.2
golang.org/x/crypto/blowfish
golang.org/x/crypto/bcrypt
github.com/bjdgyc/anylink/pkg/utils
github.com/spf13/pflag
github.com/spf13/cobra
golang.org/x/sys/internal/unsafeheader
golang.org/x/sys/unix
github.com/fsnotify/fsnotify
github.com/hashicorp/hcl/hcl/strconv
github.com/hashicorp/hcl/hcl/token
github.com/hashicorp/hcl/hcl/ast
github.com/hashicorp/hcl/hcl/scanner
github.com/hashicorp/hcl/hcl/parser
github.com/hashicorp/hcl/json/token
github.com/hashicorp/hcl/json/scanner
github.com/hashicorp/hcl/json/parser
github.com/hashicorp/hcl
github.com/hashicorp/hcl/hcl/printer
github.com/magiconair/properties
github.com/mitchellh/mapstructure
github.com/pelletier/go-toml
github.com/spf13/afero/mem
golang.org/x/text/transform
golang.org/x/text/unicode/norm
github.com/spf13/afero
github.com/spf13/cast
github.com/spf13/jwalterweatherman
github.com/subosito/gotenv
gopkg.in/ini.v1
gopkg.in/yaml.v2
github.com/spf13/viper
github.com/bjdgyc/anylink/base
github.com/asdine/storm/v3/codec
github.com/asdine/storm/v3/codec/json
go.etcd.io/bbolt
github.com/asdine/storm/v3/internal
github.com/asdine/storm/v3/index
github.com/asdine/storm/v3/q
github.com/asdine/storm/v3
github.com/xlzd/gotp
github.com/bjdgyc/anylink/dbdata
golang.org/x/time/rate
github.com/bjdgyc/anylink/sessdata
github.com/dgrijalva/jwt-go
github.com/gorilla/mux
github.com/shirou/gopsutil/internal/common
github.com/tklauser/numcpus
github.com/tklauser/go-sysconf
github.com/shirou/gopsutil/cpu
github.com/shirou/gopsutil/disk
github.com/shirou/gopsutil/host
github.com/shirou/gopsutil/load
github.com/shirou/gopsutil/mem
github.com/skip2/go-qrcode/bitset
github.com/skip2/go-qrcode/reedsolomon
github.com/skip2/go-qrcode
github.com/xhit/go-simple-mail/v2
github.com/bjdgyc/anylink/admin
github.com/google/gopacket
github.com/google/gopacket/layers
golang.org/x/net/internal/iana
golang.org/x/net/internal/socket
golang.org/x/net/bpf
golang.org/x/net/ipv4
golang.org/x/net/ipv6
golang.org/x/net/icmp
github.com/bjdgyc/anylink/pkg/arpdis
github.com/bjdgyc/anylink/pkg/proxyproto
github.com/pion/dtls/v2/internal/util
github.com/pion/dtls/v2/pkg/crypto/ccm
golang.org/x/crypto/curve25519/internal/field
golang.org/x/crypto/curve25519
github.com/pion/dtls/v2/pkg/crypto/elliptic
github.com/pion/dtls/v2/pkg/protocol
github.com/pion/dtls/v2/pkg/crypto/prf
github.com/pion/dtls/v2/pkg/protocol/alert
github.com/pion/dtls/v2/pkg/crypto/clientcertificate
github.com/pion/dtls/v2/pkg/crypto/hash
github.com/pion/dtls/v2/pkg/crypto/signature
golang.org/x/xerrors/internal
golang.org/x/xerrors
github.com/pion/dtls/v2/pkg/crypto/signaturehash
golang.org/x/crypto/cryptobyte/asn1
golang.org/x/crypto/cryptobyte
github.com/pion/dtls/v2/pkg/protocol/extension
github.com/pion/dtls/v2/pkg/protocol/handshake
github.com/pion/dtls/v2/pkg/protocol/recordlayer
github.com/pion/dtls/v2/pkg/crypto/ciphersuite
github.com/pion/dtls/v2/internal/ciphersuite
github.com/pion/dtls/v2/internal/closer
github.com/pion/logging
github.com/pion/transport/connctx
github.com/pion/transport/deadline
github.com/pion/transport/replaydetector
github.com/pion/transport/packetio
github.com/pion/udp
github.com/pion/dtls/v2
github.com/pion/dtls/v2/pkg/crypto/selfsign
github.com/songgao/packets/ethernet
github.com/songgao/water
github.com/songgao/water/waterutil
github.com/bjdgyc/anylink/handler
github.com/bjdgyc/anylink
+ RETVAL 0
+ rt=0
+ '[' 0 '!=' 0 ']'
+ echo 编译前端项目
编译前端项目
+ cd /root/anylink/web
+ npm install --registry=https://registry.npm.taobao.org
[         .........] | reify:fsevents: timing reifyNode:node_modules/watchpack-
npm WARN registry Unexpected warning for https://registry.npm.taobao.org/: Miscellaneous Warning ERR_SOCKET_TIMEOUT: request to https://cdn.npm.taobao.org/ms/-/ms-2.0.0.tgz failed, reason: Socket timeout
npm WARN registry Using stale data from https://registry.npm.taobao.org/ due to a request error during revalidation.
npm notice 
npm notice New minor version of npm available! 7.15.1 -> 7.18.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v7.18.1
npm notice Run npm install -g npm@7.18.1 to update!
npm notice 
npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! errno ERR_SOCKET_TIMEOUT
npm ERR! request to https://cdn.npm.taobao.org/ws/-/ws-6.2.1.tgz failed, reason: Socket timeout

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-18T09_52_53_279Z-debug.log
+ npm run build --registry=https://registry.npm.taobao.org

> anylink-web@0.1.0 build
> vue-cli-service build

sh: vue-cli-service: command not found
+ RETVAL 127
+ rt=127
+ '[' 127 '!=' 0 ']'
+ echo 127
127
+ exit 1
root@p1601860745:~/anylink#

怎么解决？

**Comment by bjdgyc** [comment]
```
#国内可替换源加快速度
npm install --registry=https://registry.npm.taobao.org
npm run build --registry=https://registry.npm.taobao.org
#npm install
#npm run build
```

自己改一下 `build.sh` 是因为npm源的问题。

**Comment by luckypoem** [comment]
hi.

build.sh改为了：
...
#npm install --registry=https://registry.npm.taobao.org
#npm run build --registry=https://registry.npm.taobao.org
npm install
npm run build

然后运行 ./build.sh
这次没有遇错。
不过，

root@p1601860745:~/anylink/server/conf# anylink --conf=server.toml
ServerCfg: &{ServerAddr::443 ServerDTLSAddr::4433 ServerDTLS:false AdminAddr::8800 ProxyProtocol:false DbFile:/root/anylink/server/conf/data.db CertFile:/root/anylink/server/conf/test_vpn_cert.pem CertKey:/root/anylink/server/conf/test_vpn_key.pem UiPath:/root/anylink/server/ui FilesPath:/root/anylink/server/files LogPath: LogLevel:debug Pprof:false Issuer:XX公司VPN AdminUser:admin AdminPass:$2a$10$UQ7C.EoPifDeJh6d8.31TeSPQU7hM/NOM2nixmBucJpAuXDQNqNke JwtSecret:iLmspvOiz*%ovfcs*wersdf#heR8pNU4XxBm&mW$aPCjSRMbYH#& LinkMode:tun Ipv4CIDR:192.168.10.0/24 Ipv4Gateway:192.168.10.1 Ipv4Start:192.168.10.100 Ipv4End:192.168.10.200 IpLease:1209600 MaxClient:100 MaxUserClient:3 DefaultGroup:one CstpKeepalive:20 CstpDpd:30 MobileKeepalive:40 MobileDpd:50 SessionTimeout:3600 AuthTimeout:0} 
2021/06/19 16:44:57 server.go:61: [Info] Listen admin :8800
2021/06/19 16:44:57 server.go:46: [Info] listen server :443
2021/06/19 16:44:57 main.go:26: [Info] Server pid:  2357

然后，我在浏览器里访问http://vps-public-ip:8800 ,地址跳到了http://vps-public-ip:8800/ui/ , 显示的页面内容为：
404 page not found

怎么解决 ？

**Comment by luckypoem** [comment]
哦，看到了：
“cd anylink-deploy
sudo ./anylink --conf="conf/server.toml"

不过我虽然服务器端运行起来了，但是用mac上的客户端anyconnect根本连不上服务器。其实大概1年前，就看到有人说连不上ocserve服务器了。楼主，你真的连上服务器，从而成功翻墙了吗

**Comment by bjdgyc** [comment]
本软件是企业远程办公使用，不提供翻墙功能
