### ISSUE TITLE
使用pg数据库启动报错

### ISSUE THREAD

**Issue by TedLing** [bjdgyc/anylink#341]
按照说明，使用pg数据库的时候，会报连接数据库错误

### 使用的anylink版本 ?
v0.12.2

### 使用操作系统的类型和版本?
debian12

### 使用linux 内核版本?
Linux debian 6.1.0-23-amd64

### 具体遇到的问题，可上传截图
按照readme的说明配置数据库 链接为  user:password@localhost/anylink?sslmode=verify-full  发现无法启动， 自己写代码尝试了一下，会提示 dbname is empty ，测试后发现 数据库地址要设置为  postgres://user:password@localhost/anylink?sslmode=verify-full    请更新一下readme 说明

**Comment by TedLing** [comment]
![image](https://github.com/user-attachments/assets/b21883c4-e536-4c31-a3de-f34fefceefbb)
按照这个配置 可以正常启动

**Comment by bjdgyc** [comment]
非常感谢，已修复
