### ISSUE TITLE
smtp 发送邮件 timeout 

### ISSUE THREAD

**Issue by changchunhua2017** [bjdgyc/anylink#5]
**环境**
最新master代码编译

创建用户时，勾选发送邮件按钮，点击保存，无响应，过几秒服务端日志就提示超时了
smtp 相关设置的域名，在同机器上进行  ping / telnet 25 port  ，dns 解析等操作都是正常的,  确认anylink 到 smtp server 链路是通的

后台里的邮件设置（为了截图临时改值，由 xxx.cn 代替）
![企业微信截图_16104327488362](https://user-images.githubusercontent.com/32860151/104278052-eec28680-54e2-11eb-869e-a890c8439a4e.png)

**服务端日志报错**
```
2021/01/12 14:21:46 main.go:26: [Info] Server pid:  3470
2021/01/12 14:21:46 server.go:47: [Info] listen server :443
2021/01/12 14:21:46 server.go:58: [Info] Listen admin :8800

2021/01/12 14:22:30 common.go:96: [Error] Mail Error: SMTP Connection timed out
2021/01/12 14:22:34 common.go:96: [Error] Mail Error: SMTP Connection timed out
```

**Comment by bjdgyc** [comment]
你好，我使用163.com的邮箱测试正常
1. 新版增加了邮件发送错误信息，建议升级后观察下
2. 本机安装 postfix， 使用 127.0.0.1:25 测试下

**Comment by changchunhua2017** [comment]
> 你好，我使用163.com的邮箱测试正常
> 
> 1. 新版增加了邮件发送错误信息，建议升级后观察下
> 2. 本机安装 postfix， 使用 127.0.0.1:25 测试下


pull 了最新代码编译了一版 ， 日志貌似没有打印更多信息，还和以前一样  
log_level 设置感觉没起作用，info 和debug 输出信息都差不多 

```
2021/01/13 09:25:33 main.go:26: [Info] Server pid:  9486
2021/01/13 09:25:33 server.go:47: [Info] listen server :443
2021/01/13 09:25:33 server.go:58: [Info] Listen admin :8800

2021/01/13 09:25:45 common.go:96: [Error] Mail Error: SMTP Connection timed out
2021/01/13 09:25:52 common.go:96: [Error] Mail Error: SMTP Connection timed out
```

**Comment by bjdgyc** [comment]
https://github.com/bjdgyc/anylink/commit/dd83b330ebfe0ec7c80a63c338046a30c17dd496
