### ISSUE TITLE
如何禁用anylink分发dns地址

### ISSUE THREAD

**Issue by houhuijian** [bjdgyc/anylink#65]
使用anyconnect连接后，所有的域名解析都会从vpn通道请求，会导致请求网站很慢，如果禁用anyconnect分配dns地址的优先级
https://blog.oasisfeng.com/2010/05/25/solve-the-dns-priority-issue-in-cisco-anyconnect-vpn-client/

**Comment by bjdgyc** [comment]
这个是客户端的解决方案，这个anylink做不到

**Comment by houhuijian** [comment]
> 这个是客户端的解决方案，这个anylink做不到

可能没有将明白，我的意思就是anylink可以实现类似如下cisco的解决方案吗https://www.cisco.com/c/zh_cn/support/docs/security/anyconnect-secure-mobility-client/200395-Interop-between-AnyConnect-and-the-OpenD.html#anc8

**Comment by s3cu1n4** [comment]
注释掉 link_tunnel.go的
`for _, v := range cSess.Group.ClientDns {
			HttpAddHeader(w, "X-CSTP-DNS", v.Val)
		}` 就可以了，
另外，可以加一个判断例如
` if cSess.Group.AllowDns {
		for _, v := range cSess.Group.ClientDns {
			HttpAddHeader(w, "X-CSTP-DNS", v.Val)
		}
	}`

，在后台实现启用或者禁用VPN的dns功能，

**Comment by bjdgyc** [comment]
不下发dns的话，mac和iPhone会导致无法上网

**Comment by s3cu1n4** [comment]
我们自己加了这个功能，不下发dns，mac和iPhone目前使用正常啊

**Comment by bjdgyc** [comment]
可以把改动提交上来

**Comment by bjdgyc** [comment]
已经添加支持不下发dns信息
