### ISSUE TITLE
Windows 7 x64问题

### ISSUE THREAD

**Issue by macaty** [bjdgyc/anylink#67]
server: 0.62
client：anyconnect-win7-4.7.04056
连接报
![Snipaste_2021-12-24_16-07-02](https://user-images.githubusercontent.com/16797633/147332966-9c968e1a-0bc3-4c88-b4f9-400a70dbc508.jpg)
错

**Comment by bjdgyc** [comment]
安装 anyconnect-4.8 以上版本
