### ISSUE TITLE
profile.xml 应该是独立文件，并允许配置文件路径

### ISSUE THREAD

**Issue by itviewer** [bjdgyc/anylink#68]
profile 的内容每个服务器可能不一样，需要自定义，不应该写死，应该在配置文件里定义文件路径，并动态读取返回给客户端

**Comment by itviewer** [comment]
如果不想增加配置，可以扔到 files 目录，如果有 profile.xml 这个文件就读取，没有的话再使用默认的

**Comment by bjdgyc** [comment]
已经修改到files目录下

**Comment by s3cu1n4** [comment]
直接改 files 目录下的profile.xml 不行，客户端会校验profile.xml文件的hash。

**Comment by itviewer** [comment]
@s3cu1n4 
你试过？我这里随便改 profile.xml 文件，annconnect 的客户端都可以正常接收

profile.xml 文件是个性化的服务端配置文件，尤其是其中的 `<ServerList>` 字段，需要根据服务端实际域名配置。每个服务器都不一样，不应该存在校验hash的情况

**Comment by itviewer** [comment]
@bjdgyc @s3cu1n4 
我也重现了这个问题，看来需要在运行时计算 profile.xml  文件的 sha1 ，然后传递给模板变量

**Comment by bjdgyc** [comment]
已经修复
