### ISSUE TITLE
想请加下为什么不能使用自签领证书的问题

### ISSUE THREAD

**Issue by aiminickwong** [bjdgyc/anylink#72]
想请加下为什么不能使用自签领证书的问题，如果可以使用自签名证书+仅域名绑定（动态IP）那就太好了

**Comment by bjdgyc** [comment]
使用自签名证书，技术复杂度比较高，默认不推荐。
如果有这个需求，请参考这篇文章：
https://github.com/bjdgyc/anylink/issues/71
