### ISSUE TITLE
首页在线人数统计曲线什么时候完成?

### ISSUE THREAD

**Issue by sincere518** [bjdgyc/anylink#86]
首页在线人数统计曲线什么时候完成?

**Comment by changchunhua2017** [comment]
> 首页在线人数统计曲线什么时候完成?

人家免费贡献代码 维护项目，尼玛在你这变成理所当然了   ！  你行你自己搞啊 ，不行出钱出资源啊

**Comment by sincere518** [comment]
> > 首页在线数据统计曲线什么时候完成？
> 
> 人家免费代码贡献维护项目，尼玛在你这变成理所当然了！你行你自己搞啊，不能出钱出资源啊

你脑子有问题吧？ 我只是问一下 这块功能什么时候能上线？ 和理所应当不理所应当有什么关系？你又给人家作者出了多少钱呢？出了多少资源呢？ 别回复！ 呵呵。

**Comment by lanrenwo** [comment]
@sincere518 已经上线beta版本。
