### ISSUE TITLE
docker启动不会自动修改转发

### ISSUE THREAD

**Issue by lihaiz** [bjdgyc/anylink#89]
官方原配置文件为：
#客户端分配的ip地址池
ipv4_master = "eth0"
ipv4_cidr = "192.168.10.0/24"
当改为：
#客户端分配的ip地址池
ipv4_master = "eth0"
ipv4_cidr = "192.168.100.0/24"
的时候，启动docker，
默认的转发还是
MASQUERADE  all  --  192.168.10.0/24      0.0.0.0/0
希望后续能修正为自动根据这个网段自动修改转发

**Comment by bjdgyc** [comment]
docker 启动的时候 可以通过环境变量设置

`-e IPV4_CIDR=192.168.10.0/24`

**Comment by lihaiz** [comment]
嗯，希望能自动根据server.toml去生效，这样通过配置文件就可以生效会更好

**Comment by taiwan-king** [comment]
2024/03/18 22:29:15 link_tun.go:55: [Error] running [/sbin/iptables -t nat -I POSTROUTING 1 -s 192.168.10.0/24 -o eth0 -m comment --comment AnyLink -j MASQUERADE --wait]: exit status 1: Warning: Extension comment revision 0 not supported, missing kernel module?
iptables: No chain/target/match by that name.

2024/03/18 22:29:15 link_tun.go:62: [Error] running [/sbin/iptables -t filter -I FORWARD 1 -m comment --comment AnyLink -j ACCEPT --wait]: exit status 1: Warning: Extension comment revision 0 not supported, missing kernel module?
iptables: No chain/target/match by that name.

開機自動設定NAT沒有生效變成每次重開機都要自己設定

-e IPV4_CIDR=192.168.10.0/24
測試過沒用

**Comment by bjdgyc** [comment]
@taiwan-king  麻烦发下  系统版本，系统架构，系统内核，anylink版本

**Comment by taiwan-king** [comment]
> @taiwan-king 麻烦发下 系统版本，系统架构，系统内核，anylink版本，iptables 版本

synology NAS DS1621+

![1710930645946](https://github.com/bjdgyc/anylink/assets/24381898/bbba3e27-6c8c-46dc-b0ba-1b41e9d450d0)

![1710930631846](https://github.com/bjdgyc/anylink/assets/24381898/1c635ba8-6a07-489d-b126-c63aadc728db)

![1710930726120](https://github.com/bjdgyc/anylink/assets/24381898/3e7b93bd-617f-45dc-a96b-05f807d992b5)

**Comment by bjdgyc** [comment]
在宿主机执行 `modprobe xt_comment`
并且开启docker的特权模式运行 anylink

**Comment by taiwan-king** [comment]
> 在宿主机执行 `modprobe xt_comment` 并且开启docker的特权模式运行 anylink
> 
> 使用 v0.11.4 测试一下

感謝您的快速處理,
更新新版本即正常使用不需要特別去宿主機安裝xt_comment
